import { CASING_OPTIONS, FONT_OPTIONS } from "board-to-pdf";
import { Template } from "types";

export const alphabetChart: Template = {
  templateFeatured: false,
  templateCategory: "Alphabet Charts",
  templateSubcategory: "Alphabet Charts",
  templateShortDescription: "Create an alphabet chart with custom colors",

  templateVariables: [
    {
      id: "colorScheme",
      description: "Colour scheme",
      defaultValue: "basic",
      name: "Colour Scheme",
      type: "preset",
      presets: [
        {
          value: "basic",
          description: "Basic",
          label: "Basic",
          variableValues: [
            { id: "textColorOnBackground", value: "rgb(0,0,0)" },
            {
              id: "fullBackgroundColor",
              value: "rgb(255,255,255)",
            },
            {
              id: "numberBackgroundColor",
              value: "rgb(255,255,255)",
            },
            {
              id: "consonantBackgroundColor",
              value: "rgb(255,255,255)",
            },
            {
              id: "vowelBackgroundColor",
              value: "rgb(255,255,255)",
            },
            {
              id: "punctuationBackgroundColor",
              value: "rgb(255,255,255)",
            },
            {
              id: "commandBackgroundColor",
              value: "rgb(255,255,255)",
            },
            {
              id: "emptySpaceBackgroundColor",
              value: "rgb(255,255,255)",
            },

            {
              id: "numberTextColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "consonantTextColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "vowelTextColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "punctuationTextColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "commandTextColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "emptySpaceTextColor",
              value: "rgb(0,0,0)",
            },

            {
              id: "numberBorderColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "consonantBorderColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "vowelBorderColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "punctuationBorderColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "commandBorderColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "emptySpaceBorderColor",
              value: "rgb(0,0,0)",
            },
          ],
        },
        {
          value: "green-with-highlights",
          description: "Green with highlights",
          label: "Green with highlights",
          variableValues: [
            { id: "textColorOnBackground", value: "rgb(255,255,255)" },

            {
              id: "fullBackgroundColor",
              value: "rgb(55,126,34)",
            },
            {
              id: "numberBackgroundColor",
              value: "rgb(232,240,215)",
            },
            {
              id: "consonantBackgroundColor",
              value: "rgb(255,255,255)",
            },
            {
              id: "vowelBackgroundColor",
              value: "rgb(189,211,136)",
            },
            {
              id: "punctuationBackgroundColor",
              value: "rgb(232,240,215)",
            },
            {
              id: "commandBackgroundColor",
              value: "rgb(232,240,215)",
            },
            {
              id: "emptySpaceBackgroundColor",
              value: "rgb(255,255,255)",
            },

            {
              id: "numberTextColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "consonantTextColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "vowelTextColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "punctuationTextColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "commandTextColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "emptySpaceTextColor",
              value: "rgb(0,0,0)",
            },

            {
              id: "numberBorderColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "consonantBorderColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "vowelBorderColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "punctuationBorderColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "commandBorderColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "emptySpaceBorderColor",
              value: "rgb(0,0,0)",
            },
          ],
        },
        {
          value: "purple-with-highlights",
          description: "Purple with highlights",
          label: "Purple with highlights",
          variableValues: [
            { id: "textColorOnBackground", value: "rgb(255,255,255)" },

            {
              id: "fullBackgroundColor",
              value: "rgb(68,8,125)",
            },
            {
              id: "numberBackgroundColor",
              value: "rgb(249,219,253)",
            },
            {
              id: "consonantBackgroundColor",
              value: "rgb(255,255,255)",
            },
            {
              id: "vowelBackgroundColor",
              value: "rgb(244,181,250)",
            },
            {
              id: "punctuationBackgroundColor",
              value: "rgb(249,219,253)",
            },
            {
              id: "commandBackgroundColor",
              value: "rgb(249,219,253)",
            },
            {
              id: "emptySpaceBackgroundColor",
              value: "rgb(255,255,255)",
            },

            {
              id: "numberTextColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "consonantTextColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "vowelTextColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "punctuationTextColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "commandTextColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "emptySpaceTextColor",
              value: "rgb(0,0,0)",
            },

            {
              id: "numberBorderColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "consonantBorderColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "vowelBorderColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "punctuationBorderColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "commandBorderColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "emptySpaceBorderColor",
              value: "rgb(0,0,0)",
            },
          ],
        },
        {
          value: "blue-with-highlights",
          description: "Blue with highlights",
          label: "Blue with highlights",
          variableValues: [
            { id: "textColorOnBackground", value: "rgb(255,255,255)" },

            {
              id: "fullBackgroundColor",
              value: "rgb(60,70,108)",
            },
            {
              id: "numberBackgroundColor",
              value: "rgb(216,220,233)",
            },
            {
              id: "consonantBackgroundColor",
              value: "rgb(255,255,255)",
            },
            {
              id: "vowelBackgroundColor",
              value: "rgb(178,185,212)",
            },
            {
              id: "punctuationBackgroundColor",
              value: "rgb(216,220,233)",
            },
            {
              id: "commandBackgroundColor",
              value: "rgb(216,220,233)",
            },
            {
              id: "emptySpaceBackgroundColor",
              value: "rgb(255,255,255)",
            },

            {
              id: "numberTextColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "consonantTextColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "vowelTextColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "punctuationTextColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "commandTextColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "emptySpaceTextColor",
              value: "rgb(0,0,0)",
            },

            {
              id: "numberBorderColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "consonantBorderColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "vowelBorderColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "punctuationBorderColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "commandBorderColor",
              value: "rgb(0,0,0)",
            },
            {
              id: "emptySpaceBorderColor",
              value: "rgb(0,0,0)",
            },
          ],
        },
      ],
    },
    {
      id: "casing",
      description: "Change the casing of the label",
      name: "Label casing",
      defaultValue: "capital",
      type: "option",
      options: CASING_OPTIONS,
    },
    {
      id: "fullBackgroundColor",
      description: "The color of the background",
      type: "color",
      name: "Background Color",
      defaultValue: "rgb(255,255,255)",
    },

    {
      id: "numberBackgroundColor",
      description: "The color of the background",
      type: "color",
      name: "Background Color",
      defaultValue: "rgb(255,255,255)",
    },
    {
      id: "consonantBackgroundColor",
      description: "The color of the background",
      type: "color",
      name: "Background Color",
      defaultValue: "rgb(255,255,255)",
    },
    {
      id: "vowelBackgroundColor",
      description: "The color of the background",
      type: "color",
      name: "Background Color",
      defaultValue: "rgb(255,255,255)",
    },
    {
      id: "punctuationBackgroundColor",
      description: "The color of the background",
      type: "color",
      name: "Background Color",
      defaultValue: "rgb(255,255,255)",
    },
    {
      id: "commandBackgroundColor",
      description: "The color of the background",
      type: "color",
      name: "Background Color",
      defaultValue: "rgb(255,255,255)",
    },
    {
      id: "emptySpaceBackgroundColor",
      description: "The color of the background",
      type: "color",
      name: "Background Color",
      defaultValue: "rgb(255,255,255)",
    },

    {
      id: "numberTextColor",
      description: "The color of the background",
      type: "color",
      name: "Background Color",
      defaultValue: "rgb(255,255,255)",
    },
    {
      id: "consonantTextColor",
      description: "The color of the background",
      type: "color",
      name: "Background Color",
      defaultValue: "rgb(255,255,255)",
    },
    {
      id: "vowelTextColor",
      description: "The color of the background",
      type: "color",
      name: "Background Color",
      defaultValue: "rgb(255,255,255)",
    },
    {
      id: "punctuationTextColor",
      description: "The color of the background",
      type: "color",
      name: "Background Color",
      defaultValue: "rgb(255,255,255)",
    },
    {
      id: "commandTextColor",
      description: "The color of the background",
      type: "color",
      name: "Background Color",
      defaultValue: "rgb(255,255,255)",
    },
    {
      id: "emptySpaceTextColor",
      description: "The color of the background",
      type: "color",
      name: "Background Color",
      defaultValue: "rgb(255,255,255)",
    },

    {
      id: "numberBorderColor",
      description: "The color of the background",
      type: "color",
      name: "Background Color",
      defaultValue: "rgb(255,255,255)",
    },
    {
      id: "consonantBorderColor",
      description: "The color of the background",
      type: "color",
      name: "Background Color",
      defaultValue: "rgb(255,255,255)",
    },
    {
      id: "vowelBorderColor",
      description: "The color of the background",
      type: "color",
      name: "Background Color",
      defaultValue: "rgb(255,255,255)",
    },
    {
      id: "punctuationBorderColor",
      description: "The color of the background",
      type: "color",
      name: "Background Color",
      defaultValue: "rgb(255,255,255)",
    },
    {
      id: "commandBorderColor",
      description: "The color of the background",
      type: "color",
      name: "Background Color",
      defaultValue: "rgb(255,255,255)",
    },
    {
      id: "emptySpaceBorderColor",
      description: "The color of the background",
      type: "color",
      name: "Background Color",
      defaultValue: "rgb(255,255,255)",
    },

    {
      id: "gap",
      description: "The gap between cells",
      type: "number",
      name: "Spacing",
      defaultValue: "2",
      max: 10,
      min: 0,
    },
    {
      type: "option",
      id: "font",
      description: "Choose the font used in the file",
      name: "Font",
      defaultValue: "helvetica",
      options: FONT_OPTIONS,
    },
    {
      type: "color",
      id: "textColorOnBackground",
      description: "textColorOnBackground",
      name: "textColorOnBackground",
      defaultValue: "rgb(0,0,0)",
    },
  ],
  templateVariableGroups: [
    {
      openByDefault: false,
      name: "Background Colours",
      id: "background-colours",
      description: "Change the background colour of each cell type",
      variables: [
        "fullBackgroundColor",
        "numberBackgroundColor",
        "consonantBackgroundColor",
        "vowelBackgroundColor",
        "punctuationBackgroundColor",
        "commandBackgroundColor",
        "emptySpaceBackgroundColor",
      ],
    },
    {
      openByDefault: false,
      name: "Border Colours",
      id: "border-colours",
      description: "Change the border colour of each cell type",
      variables: [
        "numberBorderColor",
        "consonantBorderColor",
        "vowelBorderColor",
        "punctuationBorderColor",
        "commandBorderColor",
        "emptySpaceBorderColor",
      ],
    },
    {
      openByDefault: false,
      name: "Text Colours",
      id: "text-colours",
      description: "Change the background text of each cell type",
      variables: [
        "numberTextColor",
        "consonantTextColor",
        "vowelTextColor",
        "punctuationTextColor",
        "commandTextColor",
        "emptySpaceTextColor",
      ],
    },
  ],
  templateId: "alphabet-chart-launchpad",
  templateDateCreated: "2022-07-20T12:00:00+01:00",
  templateDescription: "Create an alphabet chart with custom colors",
  templateName: "Alphabet Chart Template",
  templateImageUrl: "alphabet-chart.png",

  format: "open-board-0.1",
  id: "alphabet-chart-launchpad",
  locale: "en-GB",
  name: "Alphabet Chart",
  description_html: "Alphabet board to allow individuals to spell",
  ext_launchpad_options: {
    padding: 10,
    gap: { id: "gap", type: "TemplateItem" },
    button_radius: 0,
    button_border_width: 1,
    text_color_on_background: {
      id: "textColorOnBackground",
      type: "TemplateItem",
    },
    full_background_color: { id: "fullBackgroundColor", type: "TemplateItem" },
  },
  buttons: [
    {
      id: "1",
      label: "1",
      border_color: { id: "numberBorderColor", type: "TemplateItem" },
      background_color: { id: "numberBackgroundColor", type: "TemplateItem" },
      ext_launchpad_label_color: {
        id: "numberTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "2",
      label: "2",
      border_color: { id: "numberBorderColor", type: "TemplateItem" },
      background_color: { id: "numberBackgroundColor", type: "TemplateItem" },
      ext_launchpad_label_color: {
        id: "numberTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "3",
      label: "3",
      border_color: { id: "numberBorderColor", type: "TemplateItem" },
      background_color: { id: "numberBackgroundColor", type: "TemplateItem" },
      ext_launchpad_label_color: {
        id: "numberTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "4",
      label: "4",
      border_color: { id: "numberBorderColor", type: "TemplateItem" },
      background_color: { id: "numberBackgroundColor", type: "TemplateItem" },
      ext_launchpad_label_color: {
        id: "numberTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "5",
      label: "5",
      border_color: { id: "numberBorderColor", type: "TemplateItem" },
      background_color: { id: "numberBackgroundColor", type: "TemplateItem" },
      ext_launchpad_label_color: {
        id: "numberTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "6",
      label: "6",
      border_color: { id: "numberBorderColor", type: "TemplateItem" },
      background_color: { id: "numberBackgroundColor", type: "TemplateItem" },
      ext_launchpad_label_color: {
        id: "numberTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "7",
      label: "7",
      border_color: { id: "numberBorderColor", type: "TemplateItem" },
      background_color: { id: "numberBackgroundColor", type: "TemplateItem" },
      ext_launchpad_label_color: {
        id: "numberTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "8",
      label: "8",
      border_color: { id: "numberBorderColor", type: "TemplateItem" },
      background_color: { id: "numberBackgroundColor", type: "TemplateItem" },
      ext_launchpad_label_color: {
        id: "numberTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "9",
      label: "9",
      border_color: { id: "numberBorderColor", type: "TemplateItem" },
      background_color: { id: "numberBackgroundColor", type: "TemplateItem" },
      ext_launchpad_label_color: {
        id: "numberTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "0",
      label: "0",
      border_color: { id: "numberBorderColor", type: "TemplateItem" },
      background_color: { id: "numberBackgroundColor", type: "TemplateItem" },
      ext_launchpad_label_color: {
        id: "numberTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "a",
      label: "A",
      border_color: { id: "vowelBorderColor", type: "TemplateItem" },
      background_color: { id: "vowelBackgroundColor", type: "TemplateItem" },
      ext_launchpad_label_color: { id: "vowelTextColor", type: "TemplateItem" },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "b",
      label: "B",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "c",
      label: "C",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "d",
      label: "D",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "e",
      label: "E",
      border_color: { id: "vowelBorderColor", type: "TemplateItem" },
      background_color: { id: "vowelBackgroundColor", type: "TemplateItem" },
      ext_launchpad_label_color: { id: "vowelTextColor", type: "TemplateItem" },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "f",
      label: "F",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "g",
      label: "G",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "h",
      label: "H",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "i",
      label: "I",
      border_color: { id: "vowelBorderColor", type: "TemplateItem" },
      background_color: { id: "vowelBackgroundColor", type: "TemplateItem" },
      ext_launchpad_label_color: { id: "vowelTextColor", type: "TemplateItem" },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "j",
      label: "J",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "k",
      label: "K",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "l",
      label: "L",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "m",
      label: "M",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "n",
      label: "N",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "o",
      label: "O",
      border_color: { id: "vowelBorderColor", type: "TemplateItem" },
      background_color: { id: "vowelBackgroundColor", type: "TemplateItem" },
      ext_launchpad_label_color: { id: "vowelTextColor", type: "TemplateItem" },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "p",
      label: "P",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "q",
      label: "Q",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "r",
      label: "R",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "s",
      label: "S",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "t",
      label: "T",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "u",
      label: "U",
      border_color: { id: "vowelBorderColor", type: "TemplateItem" },
      background_color: { id: "vowelBackgroundColor", type: "TemplateItem" },
      ext_launchpad_label_color: { id: "vowelTextColor", type: "TemplateItem" },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "v",
      label: "V",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "w",
      label: "W",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "x",
      label: "X",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "y",
      label: "Y",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "z",
      label: "Z",
      border_color: { id: "consonantBorderColor", type: "TemplateItem" },
      background_color: {
        id: "consonantBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "consonantTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: ",",
      label: ",",
      border_color: { id: "punctuationBorderColor", type: "TemplateItem" },
      background_color: {
        id: "punctuationBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "punctuationTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: ".",
      label: ".",
      border_color: { id: "punctuationBorderColor", type: "TemplateItem" },
      background_color: {
        id: "punctuationBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "punctuationTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "?",
      label: "?",
      border_color: { id: "punctuationBorderColor", type: "TemplateItem" },
      background_color: {
        id: "punctuationBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "punctuationTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "!",
      label: "!",
      border_color: { id: "punctuationBorderColor", type: "TemplateItem" },
      background_color: {
        id: "punctuationBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "punctuationTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 30,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "delete",
      label: "DELETE",
      border_color: { id: "commandBorderColor", type: "TemplateItem" },
      background_color: { id: "commandBackgroundColor", type: "TemplateItem" },
      ext_launchpad_label_color: {
        id: "commandTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 20,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "delete-letter",
      label: "DELETE\nLETTER",
      border_color: { id: "commandBorderColor", type: "TemplateItem" },
      background_color: { id: "commandBackgroundColor", type: "TemplateItem" },
      ext_launchpad_label_color: {
        id: "commandTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 20,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "space",
      label: "SPACE",
      border_color: { id: "commandBorderColor", type: "TemplateItem" },
      background_color: { id: "commandBackgroundColor", type: "TemplateItem" },
      ext_launchpad_label_color: {
        id: "commandTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 20,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "start-again",
      label: "START AGAIN",
      border_color: { id: "commandBorderColor", type: "TemplateItem" },
      background_color: { id: "commandBackgroundColor", type: "TemplateItem" },
      ext_launchpad_label_color: {
        id: "commandTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 20,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "start-again-new-line",
      label: "START\nAGAIN",
      border_color: { id: "commandBorderColor", type: "TemplateItem" },
      background_color: { id: "commandBackgroundColor", type: "TemplateItem" },
      ext_launchpad_label_color: {
        id: "commandTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 20,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },

    {
      id: "empty-cell-one",
      label: "",
      border_color: { id: "emptySpaceBorderColor", type: "TemplateItem" },
      background_color: {
        id: "emptySpaceBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "emptySpaceTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 20,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "empty-cell-two",
      label: "",
      border_color: { id: "emptySpaceBorderColor", type: "TemplateItem" },
      background_color: {
        id: "emptySpaceBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "emptySpaceTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 20,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "empty-cell-three",
      label: "",
      border_color: { id: "emptySpaceBorderColor", type: "TemplateItem" },
      background_color: {
        id: "emptySpaceBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "emptySpaceTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 20,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
    {
      id: "empty-cell-four",
      label: "",
      border_color: { id: "emptySpaceBorderColor", type: "TemplateItem" },
      background_color: {
        id: "emptySpaceBackgroundColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_color: {
        id: "emptySpaceTextColor",
        type: "TemplateItem",
      },
      ext_launchpad_label_font_size: 20,
      ext_launchpad_label_font_style: "bold",
      ext_launchpad_label_casing: { type: "TemplateItem", id: "casing" },
      ext_launchpad_label_font: { type: "TemplateItem", id: "font" },
    },
  ],
  images: [],
  pages: [
    {
      id: "abc-with-numbers",
      ext_launchpad_title_shown_on_board: "ABC (with numbers)",
      grid: {
        rows: 5,
        columns: 10,
        order: [
          ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"],
          ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"],
          ["k", "l", "m", "n", "o", "p", "q", "r", "s", "t"],
          ["u", "v", "w", "x", "y", "z", ",", ".", "?", "!"],
          [
            "delete",
            "delete",
            "delete",
            "space",
            "space",
            "space",
            "space",
            "start-again",
            "start-again",
            "start-again",
          ],
        ],
      },
    },
    {
      id: "abc-no-numbers",
      ext_launchpad_title_shown_on_board: "ABC",

      grid: {
        rows: 4,
        columns: 10,
        order: [
          ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"],
          ["k", "l", "m", "n", "o", "p", "q", "r", "s", "t"],
          ["u", "v", "w", "x", "y", "z", ",", ".", "?", "!"],
          [
            "delete",
            "delete",
            "delete",
            "space",
            "space",
            "space",
            "space",
            "start-again",
            "start-again",
            "start-again",
          ],
        ],
      },
    },
    {
      id: "abc-with-numbers-and-spaces",
      ext_launchpad_title_shown_on_board: "ABC (with numbers + spaces)",
      grid: {
        rows: 6,
        columns: 10,
        order: [
          ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"],
          ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"],
          ["k", "l", "m", "n", "o", "p", "q", "r", "s", "t"],
          ["u", "v", "w", "x", "y", "z", ",", ".", "?", "!"],
          [
            "delete",
            "delete",
            "delete",
            "space",
            "space",
            "space",
            "space",
            "start-again",
            "start-again",
            "start-again",
          ],
          [
            "empty-cell-one",
            "empty-cell-one",
            "empty-cell-one",
            "empty-cell-one",
            "empty-cell-one",
            "empty-cell-two",
            "empty-cell-two",
            "empty-cell-two",
            "empty-cell-two",
            "empty-cell-two",
          ],
        ],
      },
    },
    {
      id: "abc-no-numbers-and-spaces",
      ext_launchpad_title_shown_on_board: "ABC (with spaces)",

      grid: {
        rows: 5,
        columns: 10,
        order: [
          ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"],
          ["k", "l", "m", "n", "o", "p", "q", "r", "s", "t"],
          ["u", "v", "w", "x", "y", "z", ",", ".", "?", "!"],
          [
            "delete",
            "delete",
            "delete",
            "space",
            "space",
            "space",
            "space",
            "start-again",
            "start-again",
            "start-again",
          ],
          [
            "empty-cell-one",
            "empty-cell-one",
            "empty-cell-one",
            "empty-cell-one",
            "empty-cell-one",
            "empty-cell-two",
            "empty-cell-two",
            "empty-cell-two",
            "empty-cell-two",
            "empty-cell-two",
          ],
        ],
      },
    },

    {
      id: "abc-portrait-no-space",
      ext_launchpad_title_shown_on_board: "ABC",

      orientation: "portrait",
      grid: {
        rows: 8,
        columns: 4,
        order: [
          ["a", "b", "c", "d"],
          ["e", "f", "g", "h"],
          ["i", "j", "k", "l"],
          ["m", "n", "o", "p"],
          ["q", "r", "s", "t"],
          ["u", "v", "w", "x"],
          [".", "y", "z", "?"],
          ["delete", "space", "space", "start-again-new-line"],
        ],
      },
    },
    {
      id: "abc-portrait-with-space",
      ext_launchpad_title_shown_on_board: "ABC (with space)",

      orientation: "portrait",
      grid: {
        rows: 9,
        columns: 4,
        order: [
          ["a", "b", "c", "d"],
          ["e", "f", "g", "h"],
          ["i", "j", "k", "l"],
          ["m", "n", "o", "p"],
          ["q", "r", "s", "t"],
          ["u", "v", "w", "x"],
          [".", "y", "z", "?"],
          ["delete", "space", "space", "start-again-new-line"],
          [
            "empty-cell-one",
            "empty-cell-one",
            "empty-cell-one",
            "empty-cell-one",
          ],
        ],
      },
    },
    {
      id: "qwerty-with-numbers",
      ext_launchpad_title_shown_on_board: "QWERTY (with numbers)",

      grid: {
        rows: 5,
        columns: 10,
        order: [
          ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"],
          ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p"],
          ["a", "s", "d", "f", "g", "h", "j", "k", "l", "?"],
          ["!", "z", "x", "c", "v", "b", "n", "m", ",", "."],
          [
            "delete",
            "delete",
            "delete",
            "space",
            "space",
            "space",
            "space",
            "start-again",
            "start-again",
            "start-again",
          ],
        ],
      },
    },
    {
      id: "qwerty-no-numbers",
      ext_launchpad_title_shown_on_board: "QWERTY",

      grid: {
        rows: 4,
        columns: 10,
        order: [
          ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p"],
          ["a", "s", "d", "f", "g", "h", "j", "k", "l", "?"],
          ["!", "z", "x", "c", "v", "b", "n", "m", ",", "."],
          [
            "delete",
            "delete",
            "delete",
            "space",
            "space",
            "space",
            "space",
            "start-again",
            "start-again",
            "start-again",
          ],
        ],
      },
    },
    {
      id: "qwerty-no-numbers-and-spaces",
      ext_launchpad_title_shown_on_board: "QWERTY (with spaces)",

      grid: {
        rows: 5,
        columns: 10,
        order: [
          ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p"],
          ["a", "s", "d", "f", "g", "h", "j", "k", "l", "?"],
          ["!", "z", "x", "c", "v", "b", "n", "m", ",", "."],
          [
            "delete",
            "delete",
            "delete",
            "space",
            "space",
            "space",
            "space",
            "start-again",
            "start-again",
            "start-again",
          ],
          [
            "empty-cell-one",
            "empty-cell-one",
            "empty-cell-one",
            "empty-cell-one",
            "empty-cell-one",
            "empty-cell-two",
            "empty-cell-two",
            "empty-cell-two",
            "empty-cell-two",
            "empty-cell-two",
          ],
        ],
      },
    },
    {
      id: "qwerty-with-numbers-and-spaces",
      ext_launchpad_title_shown_on_board: "QWERTY (with spaces + numbers)",

      grid: {
        rows: 6,
        columns: 10,
        order: [
          ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"],
          ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p"],
          ["a", "s", "d", "f", "g", "h", "j", "k", "l", "?"],
          ["!", "z", "x", "c", "v", "b", "n", "m", ",", "."],
          [
            "delete",
            "delete",
            "delete",
            "space",
            "space",
            "space",
            "space",
            "start-again",
            "start-again",
            "start-again",
          ],
          [
            "empty-cell-one",
            "empty-cell-one",
            "empty-cell-one",
            "empty-cell-one",
            "empty-cell-one",
            "empty-cell-two",
            "empty-cell-two",
            "empty-cell-two",
            "empty-cell-two",
            "empty-cell-two",
          ],
        ],
      },
    },
    {
      id: "frequency",
      ext_launchpad_title_shown_on_board: "FREQUENCY",

      grid: {
        rows: 6,
        columns: 6,
        order: [
          ["space", "e", "a", "r", "d", "u"],
          ["t", "o", "i", "l", "g", "v"],
          ["n", "s", "f", "y", "x", "."],
          ["h", "c", "p", "k", "j", ","],
          ["m", "b", "w", "q", "z", "?"],
          [
            "delete-letter",
            "start-again-new-line",
            "delete",
            "empty-cell-one",
            "empty-cell-two",
            "empty-cell-three",
            "empty-cell-four",
          ],
        ],
      },
    },
    {
      id: "frequency-with-row-labels",
      ext_launchpad_title_shown_on_board: "FREQUENCY (number encoded)",

      ext_launchpad_with_row_labels: true,
      grid: {
        rows: 6,
        columns: 6,
        order: [
          ["space", "e", "a", "r", "d", "u"],
          ["t", "o", "i", "l", "g", "v"],
          ["n", "s", "f", "y", "x", "."],
          ["h", "c", "p", "k", "j", ","],
          ["m", "b", "w", "q", "z", "?"],
          [
            "delete-letter",
            "start-again-new-line",
            "delete",
            "empty-cell-one",
            "empty-cell-two",
            "empty-cell-three",
            "empty-cell-four",
          ],
        ],
      },
    },
  ],
};
