import { Template } from "types";

export const jubilee: Template = {
  templateVariableGroups: [],
  templateDescription: "A board with about the Queen's Jubilee",
  templateName: "Jubilee Chart",
  templateId: "jubilee",
  templateImageUrl: "jubilee.png",
  templateVariables: [
    {
      id: "language",
      type: "preset",
      name: "Language",
      defaultValue: "english",
      description: "The language the labels are shown in",
      presets: [
        {
          label: "English",
          value: "english",
          description: "English",
          variableValues: [
            {
              id: "more-label",
              value: "more, again",
            },
            {
              id: "help-label",
              value: "help",
            },
            {
              id: "want-label",
              value: "want",
            },
            {
              id: "like-label",
              value: "like",
            },
            {
              id: "queen-elizabeth-label",
              value: "Queen Elizabeth",
            },
            {
              id: "stop-label",
              value: "stop",
            },
            {
              id: "different-label",
              value: "different",
            },
            {
              id: "look-label",
              value: "look",
            },
            {
              id: "dont-like-label",
              value: "don't like",
            },
            {
              id: "jubilee-label",
              value: "Jubilee",
            },
            {
              id: "celebrate-label",
              value: "celebrate",
            },
            {
              id: "street-party-label",
              value: "street party",
            },
            {
              id: "concert-label",
              value: "concert",
            },
            {
              id: "parade-label",
              value: "parade",
            },
            {
              id: "palace-label",
              value: "palace",
            },
          ],
        },
        {
          label: "French",
          value: "french",
          description: "French",
          variableValues: [
            {
              id: "more-label",
              value: "plus encore",
            },
            {
              id: "help-label",
              value: "aider",
            },
            {
              id: "want-label",
              value: "vouloir",
            },
            {
              id: "like-label",
              value: "comme",
            },
            {
              id: "queen-elizabeth-label",
              value: "Reine Elizabeth",
            },
            {
              id: "stop-label",
              value: "arrêt",
            },
            {
              id: "different-label",
              value: "différent",
            },
            {
              id: "look-label",
              value: "voir",
            },
            {
              id: "dont-like-label",
              value: "n'aime pas",
            },
            {
              id: "jubilee-label",
              value: "Jubilé",
            },
            {
              id: "celebrate-label",
              value: "célébrer",
            },
            {
              id: "street-party-label",
              value: "fête de rue",
            },
            {
              id: "concert-label",
              value: "concert",
            },
            {
              id: "parade-label",
              value: "parade",
            },
            {
              id: "palace-label",
              value: "palais",
            },
          ],
        },
      ],
    },
    {
      type: "freeText",
      maxLength: 20,
      id: "more-label",
      name: "more-label",
      defaultValue: "more-label",
      description: "more-label",
      hidden: true,
    },
    {
      type: "freeText",
      maxLength: 20,
      id: "help-label",
      name: "help-label",
      defaultValue: "help-label",
      description: "help-label",
      hidden: true,
    },

    {
      type: "freeText",
      maxLength: 20,
      id: "want-label",
      name: "want-label",
      defaultValue: "want-label",
      description: "want-label",
      hidden: true,
    },
    {
      type: "freeText",
      maxLength: 20,
      id: "like-label",
      name: "like-label",
      defaultValue: "like-label",
      description: "like-label",
      hidden: true,
    },
    {
      type: "freeText",
      maxLength: 20,
      id: "queen-elizabeth-label",
      name: "queen-elizabeth-label",
      defaultValue: "queen-elizabeth-label",
      description: "queen-elizabeth-label",
      hidden: true,
    },
    {
      type: "freeText",
      maxLength: 20,
      id: "stop-label",
      name: "stop-label",
      defaultValue: "stop-label",
      description: "stop-label",
      hidden: true,
    },
    {
      type: "freeText",
      maxLength: 20,
      id: "different-label",
      name: "different-label",
      defaultValue: "different-label",
      description: "different-label",
      hidden: true,
    },
    {
      type: "freeText",
      maxLength: 20,
      id: "look-label",
      name: "look-label",
      defaultValue: "look-label",
      description: "look-label",
      hidden: true,
    },
    {
      type: "freeText",
      maxLength: 20,
      id: "dont-like-label",
      name: "dont-like-label",
      defaultValue: "dont-like-label",
      description: "dont-like-label",
      hidden: true,
    },
    {
      type: "freeText",
      maxLength: 20,
      id: "jubilee-label",
      name: "jubilee-label",
      defaultValue: "jubilee-label",
      description: "jubilee-label",
      hidden: true,
    },
    {
      type: "freeText",
      maxLength: 20,
      id: "celebrate-label",
      name: "celebrate-label",
      defaultValue: "celebrate-label",
      description: "celebrate-label",
      hidden: true,
    },
    {
      type: "freeText",
      maxLength: 20,
      id: "street-party-label",
      name: "street-party-label",
      defaultValue: "street-party-label",
      description: "street-party-label",
      hidden: true,
    },
    {
      type: "freeText",
      maxLength: 20,
      id: "concert-label",
      name: "concert-label",
      defaultValue: "concert-label",
      description: "concert-label",
      hidden: true,
    },
    {
      type: "freeText",
      maxLength: 20,
      id: "parade-label",
      name: "parade-label",
      defaultValue: "parade-label",
      description: "parade-label",
      hidden: true,
    },
    {
      type: "freeText",
      maxLength: 20,
      id: "palace-label",
      name: "palace-label",
      defaultValue: "palace-label",
      description: "palace-label",
      hidden: true,
    },
    {
      id: "symbol-system",
      type: "preset",
      name: "Symbol System",
      defaultValue: "widgit",
      description: "The symbol system to use for the chart",
      presets: [
        {
          label: "PCS",
          value: "pcs",
          description: "PCS Symbols",
          variableValues: [
            { id: "more", value: "./symbols/pcs/more.png" },
            { id: "help", value: "./symbols/pcs/help.png" },
            { id: "want", value: "./symbols/pcs/want.png" },
            { id: "like", value: "./symbols/pcs/like.png" },
            {
              id: "queen-elizabeth",
              value: "./symbols/pcs/queen-elizabeth.png",
            },
            { id: "stop", value: "./symbols/pcs/stop.png" },
            { id: "different", value: "./symbols/pcs/different.png" },
            { id: "look", value: "./symbols/pcs/look.png" },
            { id: "dont-like", value: "./symbols/pcs/dont-like.png" },
            { id: "jubilee", value: "./symbols/pcs/jubilee.png" },
            { id: "celebrate", value: "./symbols/pcs/celebrate.png" },
            { id: "street-party", value: "./symbols/pcs/street-party.png" },
            { id: "concert", value: "./symbols/pcs/concert.png" },
            { id: "parade", value: "./symbols/pcs/parade.png" },
            { id: "palace", value: "./symbols/pcs/palace.png" },
          ],
        },
        {
          label: "Widgit",
          value: "widgit",
          description: "Widgit Symbols",
          variableValues: [
            { id: "more", value: "./symbols/widgit/more.png" },
            { id: "help", value: "./symbols/widgit/help.png" },
            { id: "want", value: "./symbols/widgit/want.png" },
            { id: "like", value: "./symbols/widgit/like.png" },
            {
              id: "queen-elizabeth",
              value: "./symbols/widgit/queen-elizabeth.png",
            },
            { id: "stop", value: "./symbols/widgit/stop.png" },
            { id: "different", value: "./symbols/widgit/different.png" },
            { id: "look", value: "./symbols/widgit/look.png" },
            { id: "dont-like", value: "./symbols/widgit/dont-like.png" },
            { id: "jubilee", value: "./symbols/widgit/jubilee.png" },
            { id: "celebrate", value: "./symbols/widgit/celebrate.png" },
            { id: "street-party", value: "./symbols/widgit/street-party.png" },
            { id: "concert", value: "./symbols/widgit/concert.png" },
            { id: "parade", value: "./symbols/widgit/parade.png" },
            { id: "palace", value: "./symbols/widgit/palace.png" },
          ],
        },
      ],
    },
    {
      id: "more",
      type: "imageUrl",
      name: "more",
      defaultValue: "./symbols/pcs/more.png",
      description: "more",
      hidden: true,
    },
    {
      id: "help",
      type: "imageUrl",
      name: "help",
      defaultValue: "./symbols/pcs/help.png",
      description: "help",
      hidden: true,
    },
    {
      id: "want",
      type: "imageUrl",
      name: "want",
      defaultValue: "./symbols/pcs/want.png",
      description: "want",
      hidden: true,
    },
    {
      id: "like",
      type: "imageUrl",
      name: "like",
      defaultValue: "./symbols/pcs/like.png",
      description: "like",
      hidden: true,
    },
    {
      id: "queen-elizabeth",
      type: "imageUrl",
      name: "queen-elizabeth",
      defaultValue: "./symbols/pcs/queen-elizabeth.png",
      description: "queen-elizabeth",
      hidden: true,
    },
    {
      id: "stop",
      type: "imageUrl",
      name: "stop",
      defaultValue: "./symbols/pcs/stop.png",
      description: "stop",
      hidden: true,
    },
    {
      id: "different",
      type: "imageUrl",
      name: "different",
      defaultValue: "./symbols/pcs/different.png",
      description: "different",
      hidden: true,
    },
    {
      id: "look",
      type: "imageUrl",
      name: "look",
      defaultValue: "./symbols/pcs/look.png",
      description: "look",
      hidden: true,
    },
    {
      id: "dont-like",
      type: "imageUrl",
      name: "dont-like",
      defaultValue: "./symbols/pcs/dont-like.png",
      description: "dont-like",
      hidden: true,
    },
    {
      id: "jubilee",
      type: "imageUrl",
      name: "jubilee",
      defaultValue: "./symbols/pcs/jubilee.png",
      description: "jubilee",
      hidden: true,
    },
    {
      id: "celebrate",
      type: "imageUrl",
      name: "celebrate",
      defaultValue: "./symbols/pcs/celebrate.png",
      description: "celebrate",
      hidden: true,
    },
    {
      id: "street-party",
      type: "imageUrl",
      name: "street-party",
      defaultValue: "./symbols/pcs/street-party.png",
      description: "street-party",
      hidden: true,
    },
    {
      id: "concert",
      type: "imageUrl",
      name: "concert",
      defaultValue: "./symbols/pcs/concert.png",
      description: "concert",
      hidden: true,
    },
    {
      id: "parade",
      type: "imageUrl",
      name: "parade",
      defaultValue: "./symbols/pcs/parade.png",
      description: "parade",
      hidden: true,
    },
    {
      id: "palace",
      type: "imageUrl",
      name: "palace",
      defaultValue: "./symbols/pcs/palace.png",
      description: "palace",
      hidden: true,
    },
  ],

  format: "open-board-0.1",
  id: "jubilee",
  locale: "en-GB",
  name: "Jubilee Chart",
  description_html: "A board with about the Queen's Jubilee",
  ext_launchpad_options: {},
  images: [
    {
      id: "more",
      url: { type: "TemplateItem", id: "more" },
    },
    {
      id: "help",
      url: { type: "TemplateItem", id: "help" },
    },
    {
      id: "want",
      url: { type: "TemplateItem", id: "want" },
    },
    {
      id: "like",
      url: { type: "TemplateItem", id: "like" },
    },
    {
      id: "queen-elizabeth",
      url: { type: "TemplateItem", id: "queen-elizabeth" },
    },
    {
      id: "stop",
      url: { type: "TemplateItem", id: "stop" },
    },
    {
      id: "different",
      url: { type: "TemplateItem", id: "different" },
    },
    {
      id: "look",
      url: { type: "TemplateItem", id: "look" },
    },
    {
      id: "dont-like",
      url: { type: "TemplateItem", id: "dont-like" },
    },
    {
      id: "jubilee",
      url: { type: "TemplateItem", id: "jubilee" },
    },
    {
      id: "celebrate",
      url: { type: "TemplateItem", id: "celebrate" },
    },
    {
      id: "street-party",
      url: { type: "TemplateItem", id: "street-party" },
    },
    {
      id: "concert",
      url: { type: "TemplateItem", id: "concert" },
    },
    {
      id: "parade",
      url: { type: "TemplateItem", id: "parade" },
    },
    {
      id: "palace",
      url: { type: "TemplateItem", id: "palace" },
    },
  ],
  buttons: [
    {
      id: "more",
      label: { type: "TemplateItem", id: "more-label" },
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "more",
    },
    {
      id: "help",
      label: { type: "TemplateItem", id: "help-label" },
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "help",
    },
    {
      id: "want",
      label: { type: "TemplateItem", id: "want-label" },
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "want",
    },
    {
      id: "like",
      label: { type: "TemplateItem", id: "like-label" },
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "like",
    },
    {
      id: "queen-elizabeth",
      label: { type: "TemplateItem", id: "queen-elizabeth-label" },
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "queen-elizabeth",
    },
    {
      id: "stop",
      label: { type: "TemplateItem", id: "stop-label" },
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "stop",
    },
    {
      id: "different",
      label: { type: "TemplateItem", id: "different-label" },
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "different",
    },
    {
      id: "look",
      label: { type: "TemplateItem", id: "look-label" },
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "look",
    },
    {
      id: "dont-like",
      label: { type: "TemplateItem", id: "dont-like-label" },
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "dont-like",
    },
    {
      id: "jubilee",
      label: { type: "TemplateItem", id: "jubilee-label" },
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "jubilee",
    },
    {
      id: "celebrate",
      label: { type: "TemplateItem", id: "celebrate-label" },
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "celebrate",
    },
    {
      id: "street-party",
      label: { type: "TemplateItem", id: "street-party-label" },
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "street-party",
    },
    {
      id: "concert",
      label: { type: "TemplateItem", id: "concert-label" },
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "concert",
    },
    {
      id: "parade",
      label: { type: "TemplateItem", id: "parade-label" },
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "parade",
    },
    {
      id: "palace",
      label: { type: "TemplateItem", id: "palace-label" },
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "palace",
    },
  ],

  pages: [
    {
      id: "first",
      grid: {
        rows: 3,
        columns: 5,
        order: [
          ["more", "help", "want", "like", "queen-elizabeth"],
          ["stop", "different", "look", "dont-like", "jubilee"],
          ["celebrate", "street-party", "concert", "parade", "palace"],
        ],
      },
    },
  ],
};
