import { Template } from "types";

export const jubilee: Template = {
  templateVariableGroups: [],
  templateDescription: "A board with about the Queen's Jubilee",
  templateName: "Jubilee Chart",
  templateId: "jubilee",
  templateImageUrl: "jubilee.png",
  templateVariables: [
    {
      id: "symbol-system",
      type: "preset",
      name: "Symbol System",
      defaultValue: "widgit",
      description: "The symbol system to use for the chart",
      presets: [
        {
          label: "PCS",
          value: "pcs",
          description: "PCS Symbols",
          variableValues: [
            { id: "more", value: "./symbols/pcs/more.png" },
            { id: "help", value: "./symbols/pcs/help.png" },
            { id: "want", value: "./symbols/pcs/want.png" },
            { id: "like", value: "./symbols/pcs/like.png" },
            {
              id: "queen-elizabeth",
              value: "./symbols/pcs/queen-elizabeth.png",
            },
            { id: "stop", value: "./symbols/pcs/stop.png" },
            { id: "different", value: "./symbols/pcs/different.png" },
            { id: "look", value: "./symbols/pcs/look.png" },
            { id: "dont-like", value: "./symbols/pcs/dont-like.png" },
            { id: "jubilee", value: "./symbols/pcs/jubilee.png" },
            { id: "celebrate", value: "./symbols/pcs/celebrate.png" },
            { id: "street-party", value: "./symbols/pcs/street-party.png" },
            { id: "concert", value: "./symbols/pcs/concert.png" },
            { id: "parade", value: "./symbols/pcs/parade.png" },
            { id: "palace", value: "./symbols/pcs/palace.png" },
          ],
        },
        {
          label: "Widgit",
          value: "widgit",
          description: "Widgit Symbols",
          variableValues: [
            { id: "more", value: "./symbols/widgit/more.png" },
            { id: "help", value: "./symbols/widgit/help.png" },
            { id: "want", value: "./symbols/widgit/want.png" },
            { id: "like", value: "./symbols/widgit/like.png" },
            {
              id: "queen-elizabeth",
              value: "./symbols/widgit/queen-elizabeth.png",
            },
            { id: "stop", value: "./symbols/widgit/stop.png" },
            { id: "different", value: "./symbols/widgit/different.png" },
            { id: "look", value: "./symbols/widgit/look.png" },
            { id: "dont-like", value: "./symbols/widgit/dont-like.png" },
            { id: "jubilee", value: "./symbols/widgit/jubilee.png" },
            { id: "celebrate", value: "./symbols/widgit/celebrate.png" },
            { id: "street-party", value: "./symbols/widgit/street-party.png" },
            { id: "concert", value: "./symbols/widgit/concert.png" },
            { id: "parade", value: "./symbols/widgit/parade.png" },
            { id: "palace", value: "./symbols/widgit/palace.png" },
          ],
        },
      ],
    },
    {
      id: "more",
      type: "imageUrl",
      name: "more",
      defaultValue: "./symbols/pcs/more.png",
      description: "more",
      hidden: true,
    },
    {
      id: "help",
      type: "imageUrl",
      name: "help",
      defaultValue: "./symbols/pcs/help.png",
      description: "help",
      hidden: true,
    },
    {
      id: "want",
      type: "imageUrl",
      name: "want",
      defaultValue: "./symbols/pcs/want.png",
      description: "want",
      hidden: true,
    },
    {
      id: "like",
      type: "imageUrl",
      name: "like",
      defaultValue: "./symbols/pcs/like.png",
      description: "like",
      hidden: true,
    },
    {
      id: "queen-elizabeth",
      type: "imageUrl",
      name: "queen-elizabeth",
      defaultValue: "./symbols/pcs/queen-elizabeth.png",
      description: "queen-elizabeth",
      hidden: true,
    },
    {
      id: "stop",
      type: "imageUrl",
      name: "stop",
      defaultValue: "./symbols/pcs/stop.png",
      description: "stop",
      hidden: true,
    },
    {
      id: "different",
      type: "imageUrl",
      name: "different",
      defaultValue: "./symbols/pcs/different.png",
      description: "different",
      hidden: true,
    },
    {
      id: "look",
      type: "imageUrl",
      name: "look",
      defaultValue: "./symbols/pcs/look.png",
      description: "look",
      hidden: true,
    },
    {
      id: "dont-like",
      type: "imageUrl",
      name: "dont-like",
      defaultValue: "./symbols/pcs/dont-like.png",
      description: "dont-like",
      hidden: true,
    },
    {
      id: "jubilee",
      type: "imageUrl",
      name: "jubilee",
      defaultValue: "./symbols/pcs/jubilee.png",
      description: "jubilee",
      hidden: true,
    },
    {
      id: "celebrate",
      type: "imageUrl",
      name: "celebrate",
      defaultValue: "./symbols/pcs/celebrate.png",
      description: "celebrate",
      hidden: true,
    },
    {
      id: "street-party",
      type: "imageUrl",
      name: "street-party",
      defaultValue: "./symbols/pcs/street-party.png",
      description: "street-party",
      hidden: true,
    },
    {
      id: "concert",
      type: "imageUrl",
      name: "concert",
      defaultValue: "./symbols/pcs/concert.png",
      description: "concert",
      hidden: true,
    },
    {
      id: "parade",
      type: "imageUrl",
      name: "parade",
      defaultValue: "./symbols/pcs/parade.png",
      description: "parade",
      hidden: true,
    },
    {
      id: "palace",
      type: "imageUrl",
      name: "palace",
      defaultValue: "./symbols/pcs/palace.png",
      description: "palace",
      hidden: true,
    },
  ],

  format: "open-board-0.1",
  id: "jubilee",
  locale: "en-GB",
  name: "Jubilee Chart",
  description_html: "A board with about the Queen's Jubilee",
  ext_launchpad_options: {},
  images: [
    {
      id: "more",
      url: { type: "TemplateItem", id: "more" },
    },
    {
      id: "help",
      url: { type: "TemplateItem", id: "help" },
    },
    {
      id: "want",
      url: { type: "TemplateItem", id: "want" },
    },
    {
      id: "like",
      url: { type: "TemplateItem", id: "like" },
    },
    {
      id: "queen-elizabeth",
      url: { type: "TemplateItem", id: "queen-elizabeth" },
    },
    {
      id: "stop",
      url: { type: "TemplateItem", id: "stop" },
    },
    {
      id: "different",
      url: { type: "TemplateItem", id: "different" },
    },
    {
      id: "look",
      url: { type: "TemplateItem", id: "look" },
    },
    {
      id: "dont-like",
      url: { type: "TemplateItem", id: "dont-like" },
    },
    {
      id: "jubilee",
      url: { type: "TemplateItem", id: "jubilee" },
    },
    {
      id: "celebrate",
      url: { type: "TemplateItem", id: "celebrate" },
    },
    {
      id: "street-party",
      url: { type: "TemplateItem", id: "street-party" },
    },
    {
      id: "concert",
      url: { type: "TemplateItem", id: "concert" },
    },
    {
      id: "parade",
      url: { type: "TemplateItem", id: "parade" },
    },
    {
      id: "palace",
      url: { type: "TemplateItem", id: "palace" },
    },
  ],
  buttons: [
    {
      id: "more",
      label: "more, again",
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "more",
    },
    {
      id: "help",
      label: "help",
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "help",
    },
    {
      id: "want",
      label: "want",
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "want",
    },
    {
      id: "like",
      label: "like",
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "like",
    },
    {
      id: "queen-elizabeth",
      label: "Queen Elizabeth",
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "queen-elizabeth",
    },
    {
      id: "stop",
      label: "stop",
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "stop",
    },
    {
      id: "different",
      label: "different",
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "different",
    },
    {
      id: "look",
      label: "look",
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "look",
    },
    {
      id: "dont-like",
      label: "don't like",
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "dont-like",
    },
    {
      id: "jubilee",
      label: "Jubilee",
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "jubilee",
    },
    {
      id: "celebrate",
      label: "celebrate",
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "celebrate",
    },
    {
      id: "street-party",
      label: "street party",
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "street-party",
    },
    {
      id: "concert",
      label: "concert",
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "concert",
    },
    {
      id: "parade",
      label: "parade",
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "parade",
    },
    {
      id: "palace",
      label: "palace",
      border_color: "rgb(0, 0, 0)",
      background_color: "rgb(255, 255, 255)",
      image_id: "palace",
    },
  ],

  pages: [
    {
      id: "first",
      grid: {
        rows: 3,
        columns: 5,
        order: [
          ["more", "help", "want", "like", "queen-elizabeth"],
          ["stop", "different", "look", "dont-like", "jubilee"],
          ["celebrate", "street-party", "concert", "parade", "palace"],
        ],
      },
    },
  ],
};
