import { Template } from "types";

export const variableGroup: Template = {
  templateVariables: [
    {
      type: "freeText",
      maxLength: 10,
      id: "first",
      name: "First",
      description: "First label",
      defaultValue: "First",
    },
    {
      type: "freeText",
      maxLength: 10,
      id: "second",
      name: "Second",
      description: "Second label",
      defaultValue: "Second",
    },
    {
      type: "freeText",
      maxLength: 10,
      id: "third",
      name: "Third",
      description: "Third label",
      defaultValue: "Third",
    },
    {
      type: "freeText",
      maxLength: 10,
      id: "fourth",
      name: "Fourth",
      description: "Fourth label",
      defaultValue: "Fourth",
    },
    {
      type: "freeText",
      maxLength: 10,
      id: "fifth",
      name: "Fifth",
      description: "Fifth label",
      defaultValue: "Fifth",
    },
    {
      type: "freeText",
      maxLength: 10,
      id: "sixth",
      name: "Sixth",
      description: "Sixth label",
      defaultValue: "Sixth",
    },
    {
      type: "freeText",
      maxLength: 10,
      id: "seventh",
      name: "Seventh",
      description: "Seventh label",
      defaultValue: "Seventh",
    },
    {
      type: "freeText",
      maxLength: 10,
      id: "eighth",
      name: "Eighth",
      description: "Eighth label",
      defaultValue: "Eighth",
    },
    {
      type: "freeText",
      maxLength: 10,
      id: "ninth",
      name: "Ninth",
      description: "Ninth label",
      defaultValue: "Ninth",
    },
  ],
  templateDescription: "Uses variable groups",
  templateName: "Variable Groups",
  templateId: "variable-groups",
  templateImageUrl: "three-by-three.png",
  templateVariableGroups: [
    {
      id: "second-row",
      variables: ["fourth", "fifth", "sixth"],
      name: "Second Row",
      description: "Second row closed",
      openByDefault: false,
    },
    {
      id: "random",
      name: "Random",
      variables: ["first", "ninth"],
      description: "Random open selection",
      openByDefault: true,
    },
  ],

  format: "open-board-0.1",
  id: "variable-groups",
  locale: "en-GB",
  name: "Variable Groups",
  description_html: "A board with nine tiles",
  ext_launchpad_options: {},

  buttons: [
    {
      id: "first",
      label: { type: "TemplateItem", id: "first" },
      border_color: "rgb(0, 0, 55)",
      background_color: "rgb(200, 255, 255)",
    },
    {
      id: "second",
      label: { type: "TemplateItem", id: "second" },
      border_color: "rgb(0, 0, 55)",
      background_color: "rgb(200, 255, 255)",
    },
    {
      id: "third",
      label: { type: "TemplateItem", id: "third" },
      border_color: "rgb(0, 0, 55)",
      background_color: "rgb(200, 255, 255)",
    },
    {
      id: "fourth",
      label: { type: "TemplateItem", id: "fourth" },
      border_color: "rgb(0, 0, 55)",
      background_color: "rgb(200, 255, 255)",
    },
    {
      id: "fifth",
      label: { type: "TemplateItem", id: "fifth" },
      border_color: "rgb(0, 0, 55)",
      background_color: "rgb(200, 255, 255)",
    },
    {
      id: "sixth",
      label: { type: "TemplateItem", id: "sixth" },
      border_color: "rgb(0, 0, 55)",
      background_color: "rgb(200, 255, 255)",
    },
    {
      id: "seventh",
      label: { type: "TemplateItem", id: "seventh" },
      border_color: "rgb(0, 0, 55)",
      background_color: "rgb(200, 255, 255)",
    },
    {
      id: "eighth",
      label: { type: "TemplateItem", id: "eighth" },
      border_color: "rgb(0, 0, 55)",
      background_color: "rgb(200, 255, 255)",
    },
    {
      id: "ninth",
      label: { type: "TemplateItem", id: "ninth" },
      border_color: "rgb(0, 0, 55)",
      background_color: "rgb(200, 255, 255)",
    },
  ],
  images: [],
  pages: [
    {
      id: "first",
      grid: {
        rows: 3,
        columns: 3,
        order: [
          ["first", "second", "fifth"],
          ["third", "fourth", "sixth"],
          ["seventh", "eighth", "ninth"],
        ],
      },
    },
  ],
};
