import { FONT_OPTIONS } from "board-to-pdf";
import { AllTemplateVariable } from "types";

export const STANDARD_VARIABLES: Array<AllTemplateVariable> = [
  {
    type: "number",
    name: "core-border",
    id: "core-border",
    description: "core-border",
    defaultValue: "2",
    hidden: true,
    min: 1,
    max: 10,
  },
  {
    type: "option",
    id: "font",
    description: "Choose the font used in the file",
    name: "Font",
    defaultValue: "helvetica",
    options: FONT_OPTIONS,
  },
  {
    type: "number",
    name: "non-core-border",
    id: "non-core-border",
    description: "non-core-border",
    defaultValue: "1",
    hidden: true,
    min: 1,
    max: 10,
  },
  {
    type: "freeText",
    name: "cover",
    id: "cover",
    description: "cover",
    hidden: true,
    defaultValue: "./symbol-chart-cover.pdf",
    maxLength: 100,
  },
  {
    id: "background-colour",
    name: "Background colour",
    description:
      "Change the background colour of the chart. Select white to save printer ink.",
    defaultValue: "rgb(255,255,255)",
    type: "color",
  },
  {
    id: "cell-colour",
    name: "Cell colour",
    description: "Change the colour of all the cells.",
    defaultValue: "rgb(255,255,255)",
    type: "color",
  },
  {
    id: "label-colour",
    name: "Text colour",
    description: "The colour of text in the cell",
    defaultValue: "rgb(0,0,0)",
    type: "color",
  },
  {
    id: "text-colour-on-background",
    name: "Title text colour",
    description: "The colour of title and footer text",
    defaultValue: "rgb(0,0,0)",
    type: "color",
  },
  {
    id: "gap",
    name: "Cell spacing",
    description:
      "The space between the cells. This will also affect the size of the cells.",
    type: "number",
    min: 0,
    max: 100,
    defaultValue: "3",
  },
  {
    id: "padding",
    name: "Page spacing",
    description:
      "The space on the outside edges of the page. This will also affect the size of the cells.",
    type: "number",
    min: 0,
    max: 100,
    defaultValue: "10",
  },
  {
    id: "invert-text",
    name: "Label position",
    description: "Show text above symbol",
    type: "boolean",
    defaultValue: "true",
    trueLabel: "Show label above symbol",
    falseLabel: "Show label below symbol",
  },
  {
    id: "copyright-notice",
    name: "Copyright Notice",
    description: "Copyright notice",
    type: "freeText",
    maxLength: 600,
    defaultValue: "Widgit Symbols © Widgit Software 2002-2023 www.widgit.com",
    hidden: true,
  },
  {
    id: "rows",
    type: "number",
    min: 1,
    max: 10,
    description: "rows",
    defaultValue: "1",
    name: "rows",
    hidden: true,
  },
  {
    id: "columns",
    type: "number",
    min: 1,
    max: 10,
    description: "columns",
    defaultValue: "1",
    name: "columns",
    hidden: true,
  },
  {
    id: "order",
    type: "freeText",
    maxLength: 9999,
    description: "orders",
    defaultValue: '[["left"]]',
    name: "orders",
    hidden: true,
  },
];
